### ISSUE TITLE
This is just another "Hook & Bait" to sucker you into signing up with GitHub

### ISSUE THREAD

**Issue by Sick-tired-of-Google-AD** [EECSB/Google-Search-Customizer#1]
None of the tabs will stop all the annoying ads from Google, I tried every one of their so-called steps to stop the ads and not one of them works!  The only thing that works is you having to sign in or create a login to GitHub and then give them all your information.  This is just a "Hook & Bait" SCAM to get your name, address and information about you. It is a shame and a disgrace that dishonest people are running and RUINING the internet!@

**Comment by EECSB** [comment]
This issue section is meant for reporting bugs or make features requests for the Google Search Customizer browser extension. This is a standard thing for almost every Github project. If you have an issue with Github themselves take it up with them not a random project on the site.
