### ISSUE TITLE
Unclear what browser this is for or how to install it.

### ISSUE THREAD

**Issue by apatheticposture** [EECSB/Google-Search-Customizer#10]
There is no mention in the README or description of what browser this is for or how to install the extension.  It's a great idea but I am unsure how to proceed.

**Comment by EECSB** [comment]
Hi.

You can add the extension to your browser by downloading it from the official extension websites for the following browsers:
[Chrome](https://chrome.google.com/webstore/detail/google-search-ad-remover/pdhiefmcgnjohonhoobalejfnbminlkc), [Firefox](https://addons.mozilla.org/en-US/firefox/addon/google-search-customizer/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search), [Edge](https://microsoftedge.microsoft.com/addons/detail/google-search-ad-remover-/eebiagooojcejfpkopfnehbnjljijnhl)

You can also install the extension manually: In chrome open: Extensions -> Manage Extensions -> Load Unpacked and select the folder with the downloaded files.
