### ISSUE TITLE
Not removing sales on first line

### ISSUE THREAD

**Issue by dmolnar110** [EECSB/Google-Search-Customizer#11]
Not removing the sales strip on the first line.
![Screenshot 2022-04-02 162334](https://user-images.githubusercontent.com/102879098/161399952-15087ef0-c7a3-4b32-b6d7-97098191735a.png)

**Comment by EECSB** [comment]
This should be fixed in the next release.

**Comment by dmolnar110** [comment]
Sweet, thank you. I know python and JavaScript. I would love to know how to
make an extension. Can you show me where to go learn how to do it?

Thanks,
Dan

**Comment by EECSB** [comment]
Actually I made blog post just about that: https://eecs.blog/making-a-browser-extension

**Comment by dmolnar110** [comment]
This is super helpful. Thank you so much!

Thanks,
Dan
