### ISSUE TITLE
Error in popup if...

### ISSUE THREAD

**Issue by skyfighteer** [EECSB/Google-Search-Customizer#12]
First, I'd like to tell you how much I love the way you implemented the Chrome Storage API, it had to be pretty hard, I find it awful to work with. Your way allows users to change things and see the results right away. I would like to thank you again for open-sourcing it, I've learned a LOT.
However, there is a bug in your implementation currently. It is easy to reproducate, despite being an edge case. **If you install the extension, and open the popup BEFORE ever going on google.com, there will be no saved configuration yet, resulting in an error.**

Now, the way I'd fix it is exactly how you fixed this issue in the content script (_edit: plus my fix added to it_), (program.js), obviously with some changes.
```
let configuration = {
    "removeUrl" : false,
    "removeArrow" : false,
    "moveUrl": false,
    "colorUrl": false,
    "adsDisplay" : "normal", //"remove", "standOut1", "standOut2"
    "searchWidget": false,
    "askWidget": false,
    "twitterWidget": false,
    "newsWidget": false,
    "mapsWidget": false,
    "sideBarWidget": false,
    "ratingsWidget": false,
    "urlColor" : "green",
    "adBackgroundColor" : "antiquewhite",
    "removeEmojis": false,
    "youtubeWidtget": false,
    "images": false,
    "mapsFindResultsOnWidget": false,
    "thingsToDoWidget": false,
    "imagesWidget": false,
    "featuredSnippet": false
};

chrome.storage.sync.get(['configuration'], function(storedConfiguration) {
    if ('configuration' in storedConfiguration) {
        storeConfig(storedConfiguration);
    }
    else {
        chrome.storage.sync.set({'configuration': configuration}, function(){});
        chrome.storage.sync.get(['configuration'], function(storedConfiguration) {
            storeConfig(storedConfiguration);
        });
    }
});
function storeConfig(storedConfiguration) {
    configuration = storedConfiguration;
    setUI(configuration["configuration"]);
}
```

**Comment by skyfighteer** [comment]
The storeConfig part of the else section is obviously only really useful if the default config is not "everything is default".

**Comment by EECSB** [comment]
Hi.

Nice to hear this is helping you learn. Also thank you for taking an interest in this project and contributing. But I suggest you download the repository, change the code, and submit a pull request. Then I can add your code to the repository and it will be visible as your contribution.

**Comment by EECSB** [comment]
Your code from the pull request was merged. Thanks.
