### ISSUE TITLE
Error in page if...

### ISSUE THREAD

**Issue by skyfighteer** [EECSB/Google-Search-Customizer#13]
So while fixing the other bug I submitted, I noticed an other one. It is also easy to reproducate, despite being an edge case. **If you install the extension, and go on a google search result page for the first time, there will be no saved configuration yet, resulting in an error.**

You tried to solve this, and it does actually get solved, but only after you opened the page for the 2nd time. 

What seems to happen is the following:
First time you open a page, this chunk of code runs from "program.js":
```
else
chrome.storage.sync.set({'configuration': configuration}, function(){});
modifySearchResults(configuration["configuration"]);
```

You can see why it is not a problem the second time around: you set the default config in the storage.
But first time, it runs the "modifySearchResults" function without having a configuration.
The way I'd solve it is the following: (Though I have a feeling it could be solved somehow more efficiently)
```
chrome.storage.sync.get(['configuration'], function(storedConfiguration) {
  if ('configuration' in storedConfiguration) {
      sendToMain(storedConfiguration);
  }
  else {
    chrome.storage.sync.set({'configuration': configuration}, function(){});
    chrome.storage.sync.get(['configuration'], function(storedConfiguration) { // this is pretty much what I added
        sendToMain(storedConfiguration); // this is pretty much what I added
    }); // this is pretty much what I added
  }
});
function sendToMain(storedConfiguration) {
  configuration = storedConfiguration;
  main(configuration["configuration"]); // send saved configuration to main
}
```

**Comment by skyfighteer** [comment]
Obviously you might as well simply move "main(configuration["configuration"]);" to the "if" part only, so it wouldn't try to run the main function the first time. It would work here, but if your default config is not "everything is false", then this is not preferable.

**Comment by EECSB** [comment]
Just like the other issue: https://github.com/EECSB/Google-Search-Customizer/issues/12#issuecomment-1105753113
If you are willing to submit the code and make a pull request I would gladly add your fix to the repository.

**Comment by skyfighteer** [comment]
All right, will do that!

**Comment by EECSB** [comment]
Your code from the pull request was merged. Thanks.
