### ISSUE TITLE
Suggestion: hide "Related searches" card from image search results

### ISSUE THREAD

**Issue by logoffon** [EECSB/Google-Search-Customizer#15]
I'd like to thank you for making this extension that eliminates Google's annoying attempts to be helpful, but failing for most of the time.
However, there's one thing this extension hasn't eliminated yet:
![image](https://user-images.githubusercontent.com/7828523/177036800-5637b901-88a1-4cdc-8eb0-566292ce7b75.png)
As you can see, the "Related searches" card (in red box) is just a nuisance as it brings up search term that's barely related to what I'm searching. Since it can be rather tricky to re-do the layout, you can simply make the card blank and optionally shift an image next to it to where the card was.

If you're wondering what the gray boxes are, they're images of websites (mostly SEO spam) I blocked using [Google Hit Hider by Domain](https://greasyfork.org/en/scripts/1682-google-hit-hider-by-domain-search-filter-block-sites).

**Comment by EECSB** [comment]
Hi. 

Thanks for the bug report. I wasn't even aware that they also stick these widgets into the image search. 
Anyway, I removed it and the image next to it takes its place. The empty space where the widget was gets moved to the end of the row.

The change will be included when I make the next release/update for the extension.
