### ISSUE TITLE
Tools section doesn't show anymore

### ISSUE THREAD

**Issue by kipusoep** [EECSB/Google-Search-Customizer#16]
Hi, thanks for writing this extension.
I noticed an issue. When I click the Tools button, the Tools section doesn't show:

![image](https://user-images.githubusercontent.com/1866549/187649488-7237da48-0d05-4ad7-a1fc-8ab83921c5b4.png)

If I disable the extension it works again.

**Comment by kipusoep** [comment]
Is this project dead?

**Comment by EECSB** [comment]
Hi.

Thanks for the bug report. The project isn't dead but I work on it in my free time and tend to forget about it. 

Anyway, this issue is now fixed and will be available in the next release(available in the next week or two).
