### ISSUE TITLE
Twitter widget is still appearing

### ISSUE THREAD

**Issue by dbjordan1** [EECSB/Google-Search-Customizer#17]
Looks like the Twitter widget removal isn't working. Version 1.2.1 in Brave.

![image](https://user-images.githubusercontent.com/36648925/189197360-3e5a0b34-c3a8-4ac3-9d4c-c65e360b38a1.png)

**Comment by EECSB** [comment]
Hi. 

Thanks for the bug report. This issue is now fixed and will be available in the next release(available in the next week or two).
