### ISSUE TITLE
Partially working, needs an update

### ISSUE THREAD

**Issue by Reggie521** [EECSB/Google-Search-Customizer#19]
Several things are not being removed anymore. IDs probably have changed. "People also search for" box (when you click a link and navigate back), "People also ask" (in the search bar dropdown), "Popular on Twitter", "Related searches", Top Sights and "More things to do". Currently using CSS to hide all this junk.

**Comment by EECSB** [comment]
Hi.

Thanks for the bug report.

The bugs should now be fixed. The update will be available in the next release(in the next week or two).

I will try to add the feature to remove the widgets in the search bar/box dropdown soon.
