### ISSUE TITLE
Removes the entire form on Google Forms with "Related Searches" option

### ISSUE THREAD

**Issue by toramanlis** [EECSB/Google-Search-Customizer#22]
The title pretty much explains it. I the options is enabled, google forms cannot show the content. Workaround is to configure the extension from chrome's extension settings to be active on only google.com

On further inspection, it's the `.O8VmIc` element having the conflict. Google images specific selector. I found that google images has `class="a3Wc3 O8VmIc"` and google forms has `class="m7w29c O8VmIc tIvQIf"` so the selector could be updated to `.a3Wc3.O8VmIc` unless I'm missing something.

**Comment by EECSB** [comment]
Hi. 

thanks for the bug report. The bug should be fixed now. 

There was already a function(it didn't work properly) to determine if the current page is the Google search engine and not some other Google domain.

I changed the function like [so](https://github.com/EECSB/Google-Search-Customizer/commit/8076a6b4b0971389662c18391f7e4dcc24a94c16). This should do a better job of determining if the current page is the search engine.
