### ISSUE TITLE
Addon not working with the Opera Browser

### ISSUE THREAD

**Issue by IzzLenn** [EECSB/Google-Search-Customizer#24]
addon always says: Please refresh the page for the changes to take full effect!
after refresh nothing has changed

downloaded via chrome webstore
Browser: Opera
Browserversion: 107.0.5045.36
Addonversion: 1.2.8

**Comment by EECSB** [comment]
Hi.

Apparently, Opera doesn't allow extensions to run on search engines by default for some reason: https://forums.opera.com/topic/60194/solved-extensions-don-t-work-in-search-engines

You need to go to your extension settings(opera://extensions) and check the "Allow access to search page results" checkbox for this extension.
![image](https://github.com/EECSB/Google-Search-Customizer/assets/50377992/70f06c8e-5295-4dfb-bfa6-68f19bf25971)

**Comment by IzzLenn** [comment]
Ah yes, now it works perfectly!
Thank you very much.
