### ISSUE TITLE
Cannot auto remove elements

### ISSUE THREAD

**Issue by pitroytech** [EECSB/Google-Search-Customizer#27]
Cannot auto remove elements on firefox addon, need click extension icon after pin extension to toolbar

**Comment by EECSB** [comment]
Hi.

It seems that on Firefox you have to explicitly allow the extension to run automatically. You can do it like so:
![Screenshot_2](https://github.com/user-attachments/assets/c08e1614-bb15-4c47-a300-296b72bfd21c)
