### ISSUE TITLE
Google products completely empty 

### ISSUE THREAD

**Issue by bramvu** [EECSB/Google-Search-Customizer#28]
when i put ad settings on 'remove' google product does'nt show any results. When is put it in 'normal' it does show results. Is this normal behaviour for the addon or is this a bug?
![image](https://github.com/user-attachments/assets/469ced50-f1b7-4310-bfa5-c1dd39a1247a)

**Comment by EECSB** [comment]
Hi. 

No, this is not intended. It seems Google introduced some changes to the search results layout and this threw off the extension as the element to be removed wasn't in the usual position. 

The [issue is fixed](https://github.com/EECSB/Google-Search-Customizer/commit/a467ab2c6017fa1a3971bff545b7b82ebb0e7156) now but it might take a couple of days for chrome/firefox/edge extensions stores to approve and put the update online.

Thanks for the bug report.
