### ISSUE TITLE
Ads continue to appear after disabling them.

### ISSUE THREAD

**Issue by bound-variable** [EECSB/Google-Search-Customizer#4]

**Comment by EECSB** [comment]
Hi. 

Indeed some ads at the bottom of the page don't get removed. However, they do get colored if you set the "Ad settings" to "Stand Out".

 I will check out the issue and make an update in the next couple of days.

**Comment by EECSB** [comment]
This issue was fixed. The ads at the bottom of the page now get removed. The updated version will be out soon.
