### ISSUE TITLE
The option "Remove Arrow after URL" refers to URLs with triple colons, not arrows

### ISSUE THREAD

**Issue by bound-variable** [EECSB/Google-Search-Customizer#5]
My search results don't have URLs with arrows. They have URLs with triple colons. See attached illustration.

![arrow](https://user-images.githubusercontent.com/51193876/123442003-51877600-d589-11eb-93de-f9c2445fe65a.jpg)

**Comment by EECSB** [comment]
I believe arrows appear on the desktop while menu dots appear on mobile. Anyway, the bug is fixed in the next release.
