### ISSUE TITLE
The disabling of the News Widget doesn't work

### ISSUE THREAD

**Issue by bound-variable** [EECSB/Google-Search-Customizer#6]
When the **News Widget** is disabled, the only element removed from the search listing is the **header** of the widget. The rest of the widget remains. Please see attached screen recording.

https://user-images.githubusercontent.com/51193876/123446333-9f9e7880-d58d-11eb-9ae7-b57c635b23da.mp4

**Comment by EECSB** [comment]
Thanks for providing a video of the issue. This bug should now be fixed in the next release.
