### ISSUE TITLE
Missing one kind of ad/widget?

### ISSUE THREAD

**Issue by Kratorator** [EECSB/Google-Search-Customizer#7]
My first try shows what looks suspiciously like covert ads... In any case, it's quite annoying. Please see attached screenshot.

![Screenshot_1](https://user-images.githubusercontent.com/16257693/148229840-8141a7fd-e366-4f54-8849-9608e54592ae.png)

**Comment by EECSB** [comment]
Thanks for the bug report. The bug should be fixed in the next release.
