### ISSUE TITLE
Wrong element gets removed

### ISSUE THREAD

**Issue by skyfighteer** [EECSB/Google-Search-Customizer#8]
Hi!

https://www.google.com/search?q=remember+xy+this+is+him+now&rlz=1C1GCEA_enHU985HU985&oq=remember+xy+this+is+him+now&aqs=chrome..69i57j0i13.4391j1j7&sourceid=chrome&ie=UTF-8

When searching this link, the wrong element gets removed. This is an "Images for..." element, while my only turned on filter is News Widget.

Looking at the code, the faulty class seems to be "GmE3X". It is present here too. 

Btw, as someone who recently started learning javascript, your code is an excellent learning material! It is very clean and does not use jQuery.

**Comment by EECSB** [comment]
Hi.

Thanks for submitting the bug report. The bug should be fixed now.
The updated version will be available when it goes through the verification process of the Firefox/Chrome Extensions Store. 

Also, it's nice to hear my code is helping you.
