### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by skyfighteer** [EECSB/Google-Search-Customizer#9]
Hi!

Google Search has a 30px margin-bottom on almost every search result.

BUT, it has a 44px margin-bottom
1. on the div after the last search result (this is the only one that is always present, not a problem)
2. after the "related searches" box (if there are related searches, not a problem)
3. on every widget div (if there is a widget present; it disappears if the widget is removed, so not a problem)
4. **on the search result BEFORE a widget** (which is a problem if the widget after this result gets removed, because the extra 14px margin-bottom stays there, with no purpose)

Could you please implement a way to remove that leftover extra space after removing a widget? It really is just a minor detail, but I'd be happy to see it happen :)

Have a nice day!

**Comment by EECSB** [comment]
Hi.

I think the problem should be solved now. If not feel free to reopen this. The update with the fix will become available in the next few days.

**Comment by skyfighteer** [comment]
HI!
Thanks for the fix. :)
However, I'd like to mention a small thing: by going through _every_ element that has the class **"hlcw0c"**, you also unnecessary remove margin-bottoms that I've described as "not a problem" in my first comment, namely the 1., 2., and 3. bullet points.
You might try experimenting with setting the margin to 0 only on the div before the removed widget, something like this:
`for (let i = 0; i < elements.length; i++){   // your code already
    let node = getParentNode(elements[i], parentNum); // your code already
    node.style.display = 'none'; // your code already
    if (node.previousElementSibling !== null) { // if there is a result before a widget = widget is not the first result
      node.previousElementSibling.margin = "0px"; // set margin to 0px
    } // my code
}` // your code already

**Comment by skyfighteer** [comment]
HI!
Thanks for the fix. :)
However, I'd like to mention a small thing: by going through every element that has the class "hlcw0c", you also unnecessarily remove divs with 44px margin-bottoms that I've described as "not a problem" in my first comment, namely the 1., 2., and 3. bullet points.
You might try experimenting with something like setting the margin to 0 only on the div before the removed widget, something like this:
```
for (let i = 0; i < elements.length; i++){ // line 429
let node = getParentNode(elements[i], parentNum); // line 430
node.style.display = 'none'; // line 431
// my code
if (node.previousElementSibling !== null) { // if there is a result before the widget = widget is not the first result
  node.previousElementSibling.margin = "0px"; // set margin to 0px
}
// my code
}
```

**Comment by EECSB** [comment]
Hi. 

Before I removed the margins for all the "hlcw0c" classes as it was just easier.
Now I have implemented it the way you suggested with .previousElementSibling.

**Comment by skyfighteer** [comment]
Hi.

Thank you very much for implementing my code. It is an honor.

Bless you,
skyfighteer
